languageCode = "en-us"
languageName = "English"
displayName = "🇺🇸"
isoCode = "en-EN"
weight = 1
rtl = false

title = "Tilmann Böhme"
# logo = "img/logo.jpg"
description = "Automate your impact."
copyright = "&copy; 2022 Tilmann Böhme"

dateFormat = "02 January 2006"

[author]
name = "Tilmann Böhme"
image = "img/tilmann.jpg"
headline = "Automate your impact!"
bio = "Tilmann uses automation to scale impact."
links = [
  { twitter = "https://twitter.com/tilmannb" },
  { github = "https://github.com/tilmann" },
  { linkedin = "https://www.linkedin.com/in/tilmannb/" },
]
