languageCode = "de-de"
languageName = "Deutsch"
displayName = "🇩🇪"
isoCode = "de-DE"
weight = 2
rtl = false

title = "Tilmann Böhme"
# logo = "img/logo.jpg"
description = "IT-Expertise für die Energiewende."
copyright = "&copy; 2022 Tilmann Böhme"

dateFormat = "02 January 2006"

[author]
name = "Tilmann Böhme"
image = "img/tilmann.jpg"
headline = "IT-Expertise für die Energiewende."
bio = "Mit IT-Wissen zur Energiewende."
links = [
  { twitter = "https://twitter.com/tilmannb" },
  { github = "https://github.com/tilmann" },
  { linkedin = "https://www.linkedin.com/in/tilmannb/" },
]
