# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
name = "Expertise"
pageRef = "expertise"
weight = 10

# [[main]]
# name = "Hintergrund"
# pageRef = "bio"
# weight = 20

[[main]]
name = "Lass uns sprechen"
url = "https://tidycal.com/tilmannb/25"
weight = 100

# [[main]]
#   name = "GitHub"
#   url = "https://github.com/jpanther/congo"
#   weight = 40


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

# [[footer]]
# name = "Kontakt"
# pageRef = "contact"

[[footer]]
name = "Impressum"
pageRef = "imprint"

# [[footer]]
# name = "Privacy"
# pageRef = "privacy"


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10
